#!/usr/bin/env perl

use common::sense;
use autodie 'system';

my $compiler = $ARGV[0] or die;
my $input    = $ARGV[1] or die;

sub notdir   { ($_[0] =~ /([^\/]+)$/)[0] }
sub basename { ($_[0] =~ /(.+)\.[^.]+$/)[0] }

for (qw/xhtml xul/) {
   system $compiler, $input, "testsuite/xul/" . (basename notdir $input) . ".$_";
}
